import type { Insight } from "@/types";

export const mockInsights: Insight[] = [
  {
    id: "i_01",
    title: "4 invoices can be followed up today",
    summary: "€6,380 is 14+ days overdue across 3 clients with a good payment history.",
    rationale:
      "These clients usually pay within 3 days of a reminder. A polite follow-up now keeps the relationship intact and shortens your cash cycle.",
    priority: "high",
    status: "new",
    module: "nexo",
    confidence: 0.92,
    impact: { label: "Cash in", value: "€6,380" },
    createdAt: "2026-09-24T08:52:00.000Z",
    projectId: "p_collection",
  },
  {
    id: "i_02",
    title: "Two deals have gone quiet",
    summary: "No contact in 12 days on deals worth €24k combined. Lume found an unanswered question in one thread.",
    rationale: "Deals without contact for more than 10 days close 3× less often in your pipeline history.",
    priority: "high",
    status: "in-review",
    module: "lume",
    confidence: 0.84,
    impact: { label: "Pipeline", value: "€24,000" },
    createdAt: "2026-09-23T14:20:00.000Z",
    projectId: "p_pipeline",
  },
  {
    id: "i_03",
    title: "Kickoff scheduling can be fully automated",
    summary: "The last 9 kickoffs followed the same pattern. Volt can propose slots and send invites after contract signature.",
    rationale: "Saves roughly 45 minutes per new client and removes a step that delayed 3 onboardings last month.",
    priority: "medium",
    status: "applied",
    module: "volt",
    confidence: 0.88,
    impact: { label: "Time", value: "≈ 6h / month" },
    createdAt: "2026-09-20T10:00:00.000Z",
    projectId: "p_onboarding",
  },
  {
    id: "i_04",
    title: "Delivery team is at 118% capacity next week",
    summary: "Three deadlines overlap on Thursday. Moving one review would bring load back under 95%.",
    rationale: "Based on calendar blocks and task estimates from the last 6 weeks.",
    priority: "medium",
    status: "processing",
    module: "zento",
    confidence: 0.71,
    impact: { label: "Risk", value: "2 deadlines" },
    createdAt: "2026-09-24T06:00:00.000Z",
    projectId: "p_capacity",
  },
  {
    id: "i_05",
    title: "Monthly forecast narrative",
    summary: "Generate a written explanation of this month's numbers for your board pack.",
    rationale: "Available on the Enterprise plan with Orion Advanced.",
    priority: "low",
    status: "locked",
    module: "orion",
    confidence: 0.8,
    impact: { label: "Time", value: "≈ 3h / month" },
    createdAt: "2026-09-19T09:00:00.000Z",
    projectId: "p_quarterly",
  },
  {
    id: "i_06",
    title: "Subscription tool overlap",
    summary: "Two tools with overlapping features cost €96/month. One has not been opened in 41 days.",
    rationale: "Detected from card statements and login activity.",
    priority: "low",
    status: "dismissed",
    module: "nexo",
    confidence: 0.66,
    impact: { label: "Savings", value: "€1,152 / year" },
    createdAt: "2026-09-12T09:00:00.000Z",
    projectId: null,
  },
];
